Fix errors unregistering addon second time
Because button_classes is not cleared after addon is enabled and disabled again it will try to unregister classes that were already unregistered, leading to errors.

Related errors:

```
Exception in module unregister(): '\\Blender\\4.2\\scripts\\addons\\ScriptToButton\\__init__.py'
Traceback (most recent call last):
  File "\Blender\4.2\scripts\modules\addon_utils.py", line 537, in disable
    mod.unregister()
  File "\Blender\4.2\scripts\addons\ScriptToButton\__init__.py", line 61, in unregister
    dynamic_panels.unregister()
  File "\Blender\4.2\scripts\addons\ScriptToButton\dynamic_panels.py", line 122, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)

Error: Traceback (most recent call last):
  File "\Blender\4.2\scripts\modules\addon_utils.py", line 537, in disable
    mod.unregister()
  File "\Blender\4.2\scripts\addons\ScriptToButton\__init__.py", line 61, in unregister
    dynamic_panels.unregister()
  File "\Blender\4.2\scripts\addons\ScriptToButton\dynamic_panels.py", line 122, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
```